INSERT INTO `opinie` (`opinia_id`, `autor`, `liczba_gwiazdek`, `tresc`) VALUES
(1, 'Ewela', 3, 'Hotel raczej kiepsko polozony, do miasta 5 km. Budynki to 2 pietrowe domki, ktore nie maja nic wspolnego z obiektem kameralnym. Duzy obiekt, z dobra infrastruktura. Pokoje bardzo slabe, zle sprzatane z grzybem w lazience. Jedzenie wspaniale i roznorodne. Plaza bardzo ladna piaszczysto - zwirowa, lezaki dostepne, sporty wodne na plazy za dodatkowa oplata.'),
(2, 'Renata', 4, 'znakomity hotel cudownie spedzone wczasy wspanile widoki czysto i bardzo ladnie fajni ludzie i wszystko tam bylo fajne na pewno wrocimy tam jeszcze bo wciaz tesknimy za tymi dniami spedzonymi w tym hotelu na pewno wrocimy tam jeszcze raz'),
(3, 'Ela', 3, 'Hotel zasluguje na 3, nie 5 gwiazdek. Budynki stloczone na malenkiej przestrzeni. Pokoj brudny, przescieradla dziurawe, o papier toaletowy i wode trzeba sie bylo upominac ( z roznym skutkiem ).'),
(4, 'Sharon R', 5, 'Duzy kompleks z usmiechnieta nie natretna i bardzo zyczliwa obsluga.'),
(5, 'Bernardo F', 5, 'A nice beachfront property. You cant beat the location right on the beach. The rooms were nice and comfortable, decent mattress, and surprisingly a quiet location too. All the staff was great, we wished we stayed here longer! Priced for the tourist area.'),
(6, 'Tomasz O', 4, 'Rewelacyjne miejsce!!! Wspanialy pokoj i wspaniale centrum FITNESS oraz basen i jacuzzi. A widok rewelacyjny. :) W zasadzie nie wiem co napisac negatywnego... moze tylko to, ze w okresach swiat bardzo duzo ludzi... jednak nastepnego dnia rano pusto i przyjemnie. ;)'),
(7, 'Bartozz', 4, 'Spelnia wszystkie parametry hotelu biznesowego jak i turystycznego. Szczegolnie polecam pietro klubowe z uslugami concierge. Z gornych pieter widoki sa wspaniale'),
(8, 'Marry J', 3, 'Super miejsce, samo centrum 1 minuta od dworca, basen robi wrazenie oraz widoki. sniadania pyszne przy dzwieku harfy, obiad i kolacja rownie dobry polecam. Idealny zarowno na wyjazd biznesowy , we dwoje oraz rodzinny.'),
(9, 'Jacek G', 4, 'Rewelacyjny hotel na najwyzszym poziomie. Cos jest na rzeczy ze wyroznia sie wsrod innych hoteli najwyzszej klasy. Piekny widok z okna, super pokoje z bardzo komfortowym wielkim lozkiem.'),
(10, 'Edyta J', 5, 'Hotelu nie trzeba reklamowac Jest to luksus sam w sobie Widok z apartamentu na panorame jest zapierajacy Obsluga przemila i sluzaca pomoca na kazdym kroku Drogo ale warto Kawiarenka na parterze z pyszna kawa i goraca czekolada a na pietrze swietny bar z pysznymi drinkami'),
(11, '19Carla80', 5, 'Duze przestronne pokoje, z ogromnym lozkiem. Gustowna lazienka, pojemna szafa i nawet widok z okna nie najgorszy. Bardzo dobra kuchnia, mnogosc dan, wybor serow pieczywa ect. Polozenie w samym centrum. Blisko do dworca i na starowke'),
(12, 'Natalia S', 5, 'Bardzo dobry hostel, choc lokalizacja i wyglad zewnetrzny moga na to nie wskazywac. Obsluga mila i pomocna, wszystko bardzo dobrze zorganizowane (wejscia na kod do hostelu, pokoi, kuchni). '),
(13, 'knigth1249', 3, 'Bylismy wieksza ekipa, pokoj 5-os, przestronny, lozka pietrowe, lazienki na zewnatrz, bardzo fajna kuchnia i pokoje do wypoczynku dostepne dla wszystkich, mozna zrobic tam impreze, dobra lokalizacja, mozna smialo przejsc sie pieszo na starowke. Polecam dla zorganizowanych wiekszych grup. '),
(14, 'Magdalena K', 5, 'Wyjazd wieksza ekipa, caly pokoj do naszej dyspozycji. Pokoje bardzo ladne i przestronne, w calym hostelu czysto i swiezo, dodatkowym atutem jest duza kuchnia. Obsluga mila i pomocna. Bardzo dobra lokalizacja.')
;